# =====================================================
# DOCKER COMPOSE - NuxtJS + NGINX FRONT API
# =====================================================
# Stack Overview:
# - NuxtJS API
# - Nginx reverse proxy
# =====================================================

name: nuxtjs-master

x-nginx-image: &nginx-image nginx:1.31.1@sha256:5aca99593157f4ae539a5dec1092a0ad8762f8e2eb1789085a13a0f5622369f6

networks:
  master-netwrk:
    external: true

services:
# =====================================================
# NuxtJS BACKEND APPLICATION
# =====================================================
  nuxtjs-webgui-io:
    build: .
    container_name: ${APP_NAME}_nuxtjs-webgui-io
    # restart: always
    ports:
      - ${NUXTJS_WEBAPI_IO_PORT}:${PORT_OF_NUXTJS}
    working_dir: /var/www/app
    volumes:
      # Source code bind mount (dev-friendly)
      - ./source:/var/www/app
    env_file: .env
    networks:
      - master-netwrk

# =====================================================
# NGINX REVERSE PROXY
# =====================================================
  nginxe-server-fe:
    image: *nginx-image
    container_name: ${APP_NAME}_nginxe-server-fe
    restart: always
    ports:
      - ${NGINXE_SERVER_FE_PORT}:${PORT_OF_NGINXE}
    volumes:
      # Nginx configuration
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template
    env_file: .env
    depends_on:
      - nuxtjs-webgui-io
    networks:
      - master-netwrk
