# =====================================================
# DOCKER COMPOSE - NUXTJS + NGINX FRONT API
# =====================================================
# Stack Overview:
# - Nuxtjs API
# - Nginx reverse proxy
# =====================================================

name: beldam-nuxtjs-webapi-io

x-nginx-image: &nginx-image nginx:1.31.1@sha256:5aca99593157f4ae539a5dec1092a0ad8762f8e2eb1789085a13a0f5622369f6

networks:
  master-netwrk:
    external: true

services:
  # =====================================================
  # NUXTJS BACKEND APPLICATION
  # =====================================================
  beldam-nuxtjs-webapi-io:
    build: .
    container_name: ${APP_NAME}_nuxtjs-webapi-io
    restart: always
    ports:
      - ${NUXTJS_WEBAPI_IO_PORT}:${PORT_OF_NUXTJS}
    working_dir: /var/www/app
    volumes:
      # Source code bind mount (dev-friendly)
      - ../source:/var/www/app
    env_file: ../../.env
    networks:
      - master-netwrk

  # =====================================================
  # NGINX REVERSE PROXY
  # =====================================================
  beldam-nginxe-server-be:
    image: *nginx-image
    container_name: ${APP_NAME}_nginxe-server-be
    restart: always
    ports:
      - ${NGINXE_SERVER_BE_PORT}:${PORT_OF_NGINXE}
    volumes:
      # Nginx configuration
      - ../nginx/default.conf.template:/etc/nginx/templates/default.conf.template
    env_file: ../../.env
    depends_on:
      - beldam-nuxtjs-webapi-io
    networks:
      - master-netwrk
